---
title: "git_00"
author: "Jaci Heckman"
date: "Year 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
And think you that I should be dumb,  
And full DOLORUM OMNIUM,  
Excepting when YOU choose to come  
And share my dinner?  
At other times be sour and glum  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
I had withdrawn in forest, and my song  
Was swallowed up in leaves that blew alway;  
And to the forest edge you came one day  
(This was my dream) and looked and pondered long,  
But did not enter, though the wish was strong:  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
"Anniversary Letter"  
You give me excuse after excuse,   
With your eyes giving loving looks, your snarky comments, your comforting breaths -  
If I struggle to breathe,   
Every rocky day when we get to be together and present to hold each other afterwards.   
Every time   
I doubt myself you stay my rock.  
I will be here for you.   
I want to work for what we have, and I want us   
To always prosper,   
That is something I can wish for. But you took those wishes,   
And made them a reality.   
I am safe with you, and I am loved by you continuously.  
